server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  jpa:
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.default_batch_fetch_size: 50
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

security:
  regex:
    email-regex: '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
    password-regex: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&._-])[A-Za-z\d@$!%*?&._-]{8,}$'
  jwt:
    secret: 'probando-clave-secreta-para-hmac'   # 32+ chars
   # secret: ${JWT_SECRET}
    expiration-minutes: 1

logging:
  level:
    org.springframework.boot.context.properties: DEBUG

